In [1]:
import os, sys
import datetime
import pandas as pd
sys.path.append("../../app/data/database/")

from finance_database_service import Finance_Database_Service

In [2]:
db_service = Finance_Database_Service(db_file_path="finance.db")

In [3]:
db_service.create_bookkeeping_table()

[]

In [ ]:
db_service.add_transaction_records(
    transaction_records=[
        {
            "transaction_date": datetime.date(2026, 4, 5),
            "user": "test_user",
            "amount": 200,
            "currency": "HKD",
            "transaction_type": "支出",
            "transaction_category": "杂货",
            "site": "Marketplace",
            "comment": "蔬菜、水果、牛奶、肉"
        },
        {
            "transaction_date": datetime.date(2026, 4, 4),
            "user": "test_user",
            "amount": 100,
            "currency": "HKD",
            "transaction_type": "支出",
            "transaction_category": "交通",
            "site": "出租车",
            "comment": None,
        },
        {
            "transaction_date": datetime.date(2026, 4, 1),
            "user": "test_user",
            "amount": 100,
            "currency": "USD",
            "transaction_type": "支出",
            "transaction_category": "软件",
            "site": None,
            "comment": "Github Copilot 订阅费",
        },
        {
            "transaction_date": datetime.date(2026, 4, 20),
            "user": "test_user",
            "amount": 70000,
            "currency": "HKD",
            "transaction_type": "收入",
            "transaction_category": "工资",
            "site": "公司",
            "comment": "工资",
        }
    ]
)

In [ ]:
# db_service.delete_transaction_record_by_id(transaction_id=2)

In [4]:
data = db_service.query_latest_transaction_records(number=10)
pd.DataFrame([dict(d) for d in data])

,id,user,transaction_date,amount,currency,transaction_type,transaction_category,site,comment,modified_time
0,1,abigail,2026-02-05,200.0,HKD,支出,杂货,Park and Shop,Groceries+Utensils,2026-04-21 23:06:12
1,2,test_user,2026-04-04,100.0,HKD,支出,交通,出租车,NaN,2026-04-21 22:53:58
2,3,test_user,2026-04-01,100.0,USD,支出,软件,NaN,Github Copilot 订阅费,2026-04-21 22:53:58
3,4,test_user,2026-04-20,70000.0,HKD,收入,工资,公司,工资,2026-04-21 22:53:58

In [5]:
data

[<sqlite3.Row at 0x1f065f24b80>,
 <sqlite3.Row at 0x1f01047cbb0>,
 <sqlite3.Row at 0x1f01047caf0>,
 <sqlite3.Row at 0x1f01047c7c0>]

In [6]:
data = db_service.query_all_transaction_records()
pd.DataFrame([dict(d) for d in data])

,id,user,transaction_date,amount,currency,transaction_type,transaction_category,site,comment,modified_time
0,1,abigail,2026-02-05,200.0,HKD,支出,杂货,Park and Shop,Groceries+Utensils,2026-04-21 23:06:12
1,2,test_user,2026-04-04,100.0,HKD,支出,交通,出租车,NaN,2026-04-21 22:53:58
2,3,test_user,2026-04-01,100.0,USD,支出,软件,NaN,Github Copilot 订阅费,2026-04-21 22:53:58
3,4,test_user,2026-04-20,70000.0,HKD,收入,工资,公司,工资,2026-04-21 22:53:58

In [ ]:
data = db_service.query_transaction_records_by_criteria(
    #transaction_date_start=datetime.date(2026, 1, 1),
    #transaction_date_end=datetime.date(2026, 2, 20),
    comment="Groceries"
)
pd.DataFrame([dict(d) for d in data])

In [ ]:
db_service.update_transaction_record(
    transaction_id=1, 
    transaction_record={
        "transaction_date": datetime.date(2026, 2, 5),
        "user": "abigail",
        "amount": 200,
        "currency": "HKD",
        "transaction_type": "支出",
        "transaction_category": "杂货",
        "site": "Park and Shop",
        "comment": "Groceries+Utensils"
    }
)