In [1]:
import os, sys
import datetime
import pandas as pd
sys.path.append("../../app/data/database/")

from finance_database_service import Finance_Database_Service

In [2]:
db_service = Finance_Database_Service(db_file_path="finance.db")

In [3]:
db_service.create_bookkeeping_table()

[]

In [4]:
db_service.add_transaction_records(
    transaction_records=[
        {
            "transaction_date": datetime.date(2026, 2, 5),
            "user": "test_user",
            "amount": 200,
            "currency": "HKD",
            "transaction_category": "Food",
            "site": "Marketplace",
            "comment": "Groceries"
        },
        {
            "transaction_date": datetime.date(2026, 2, 4),
            "user": "test_user",
            "amount": 100,
            "currency": "HKD",
            "transaction_category": "Transportation",
            "site": "Taxi",
            "comment": None,
        },
        {
            "transaction_date": datetime.date(2026, 2, 1),
            "user": "test_user",
            "amount": 100,
            "currency": "USD",
            "transaction_category": "Software",
            "site": None,
            "comment": "Github Copilot Subscription",
        },
    ]
)

[]

In [ ]:
# db_service.delete_transaction_record_by_id(transaction_id=2)

[]

In [3]:
data = db_service.query_latest_transaction_records(number=10)
pd.DataFrame([dict(d) for d in data])

,id,user,transaction_date,amount,currency,transaction_category,site,comment,modified_time
0,1,test_user,2026-02-05,200.0,HKD,Food,Marketplace,Groceries,2026-02-05 16:02:13
1,2,test_user,2026-02-04,100.0,HKD,Transportation,Taxi,NaN,2026-02-05 16:02:13
2,3,test_user,2026-02-01,100.0,USD,Software,NaN,Github Copilot Subscription,2026-02-05 16:02:13

In [4]:
data = db_service.query_all_transaction_records()
pd.DataFrame([dict(d) for d in data])

,id,user,transaction_date,amount,currency,transaction_category,site,comment,modified_time
0,1,test_user,2026-02-05,200.0,HKD,Food,Marketplace,Groceries,2026-02-05 16:02:13
1,2,test_user,2026-02-04,100.0,HKD,Transportation,Taxi,NaN,2026-02-05 16:02:13
2,3,test_user,2026-02-01,100.0,USD,Software,NaN,Github Copilot Subscription,2026-02-05 16:02:13

In [3]:
data = db_service.query_transaction_records(
    transaction_categories=["Food"],
    transaction_date_start=datetime.date(2026, 1, 1),
    transaction_date_end=datetime.date(2026, 2, 20),
)
pd.DataFrame([dict(d) for d in data])

            SELECT * FROM bookkeeping WHERE
        transaction_date >= '2026-01-01' AND transaction_date <= '2026-02-20' AND transaction_category IN ('Food')

,id,user,transaction_date,amount,currency,transaction_category,site,comment,created_at
0,1,test_user,2026-02-05,100.0,HKD,Food,Marketplace,Groceries,2026-02-05 15:33:34